# Generated by Django 5.1.6 on 2025-03-03 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('building_number', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='main.category')),
            ],
        ),
        migrations.RenameModel(
            old_name='Owner',
            new_name='LandLord',
        ),
        migrations.CreateModel(
            name='RentalProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('rent_amount', models.IntegerField()),
                ('building_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.buildingaddress')),
                ('current_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.landlord')),
                ('current_tenant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tenant')),
            ],
        ),
    ]
